### PR TITLE
Add missing repo field to prevent npm warnings

### PR DESCRIPTION
**Pull request by jahed**

### CODE REVIEW

**Comment by LeonFedotov** [comment]
:+1:

**Comment by jahed** [comment]
Looks like this project is abandoned.

**Comment by LeonFedotov** [comment]
@iammerrick Sup dude, do you mind?
were getting a shitty warning every npm install -_- 
`
npm WARN package.json squirejs@0.2.0 No repository field.
`

**Comment by iammerrick** [comment]
Sure I'll take care of it. :-)

**Comment by LeonFedotov** [comment]
Thanks man :)

**Comment by iammerrick** [comment]
Hey no problem, didn't know it was bugging people so much :-) Sorry about that!

**Comment by jahed** [comment]
Thanks for merging!

**Pull request merged**
