### PR TITLE
QUnit module for squire.js

### PR DESCRIPTION
**Pull request by jaredwy**
Probably best viewed as a work in progress as i iron out the kinks but certainly will work for people who want to make their life easier with qunit.

### CODE REVIEW

**Comment by iammerrick** [comment]
@joeeames When you get some time could you review this an we can talk about it?

**Comment by jaredwy** [comment]
Yay :)

Also, have been running this at adobe with no incidents yet.

**Comment by iammerrick** [comment]
Thats terrific @jaredwy :-D. Sorry its taken me so long to review these things, work has been crazy!

**Comment by jaredwy** [comment]
Got a pull request on this to update a small typo. Makes it work on servers that are case sensitive.

**Comment by iammerrick** [comment]
I intend to tear out the test framework specific work into separate repositories later on. Thanks!

**Pull request closed without merging**
